name: tools

services:
  containered-claude:
    container_name: containered-claude
    image: my-claude-code:latest
    build:
      context: ./etc/dockerfiles/claude-code/
      args:
        USERID: ${USERID:-1000}
        GROUPID: ${GROUPID:-1000}
        TZ: ${TZ:-Asia/Tokyo}
        ADDITIONAL_CA_CERT_PATH: ${ADDITIONAL_CA_CERT_PATH:-}
    network_mode: "host"
    develop:
      watch:
        - action: rebuild
          path: ./etc/dockerfiles/claude-code/Dockerfile
    volumes:
      - type: bind
        source: ${SOURCE_PATH:-.}
        target: /workspace/
      - type: bind
        source: ${CLAUDE_CREDENTIAL_PATH:-~/.claude}
        target: /home/node/.claude
      - type: bind
        source: ${CLAUDE_CONFIG_PATH:-~/.claude.json}
        target: /home/node/.claude.json

  plantuml:
    container_name: plantuml
    image: plantuml/plantuml-server:jetty
    ports:
      - 18123:8080

  playwright:
    container_name: playwright
    image: my-playwright-mcp:latest
    environment:
      DISPLAY: :0
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    build:
      context: ./etc/dockerfiles/playwright-mcp/
    ports:
      - 8931:8931
    entrypoint:
      ["node", "cli.js", "--headless", "--browser", "chrome", "--no-sandbox", "--port", "8931"]
      # ["node", "cli.js", "--browser", "chrome", "--no-sandbox", "--port", "8931", "--block-service-workers", "--blocked-origins", "github.githubassets.com/assets/*.js;googletagmanager.com;google-analytics.com;doubleclick.net;facebook.com;twitter.com"]
      # ["node", "cli.js", "--browser", "chromium", "--no-sandbox", "--port", "8931"]
      # ["node", "cli.js", "--browser", "chromium", "--no-sandbox"]
      # ["node", "cli.js", "--headless", "--browser", "chromium", "--no-sandbox"]
      # ["node", "cli.js", "--headless", "--browser", "chrome", "--no-sandbox"]
      # ["node", "cli.js", "--headless", "--browser", "msedge", "--no-sandbox"]
      # ["node", "cli.js", "--headless", "--browser", "webkit", "--no-sandbox"]
