# MCP (Model Context Protocol) サービス設定
# このファイルでMCPサービスの環境変数要件と前提条件を定義します

# ========================================
# MCP環境変数要件定義
# ========================================
# MCPごとに必須となる環境変数を定義します
#
# 形式:
#   MCP識別子:
#     - 環境変数名1
#     - 環境変数名2

"@modelcontextprotocol/server-gitlab":
  - GITLAB_PERSONAL_ACCESS_TOKEN
  - GITLAB_API_URL

"mcp/gitlab":
  - GITLAB_PERSONAL_ACCESS_TOKEN
  - GITLAB_API_URL

# ========================================
# MCP前提条件定義
# ========================================
# MCPサービスごとに実行が必要な前提コマンドを定義します
#
# 形式:
#   サービス名:
#     prerequisites:
#       - command: 実行するコマンド
#         description: コマンドの説明
#         check: 前提条件が満たされているかのチェックコマンド（オプション）
#         host: true  # ホスト側で実行する場合（デフォルトはfalse）
#         background: true  # バックグラウンドで実行する場合（デフォルトはfalse）

playwright:
  prerequisites:
    # MCPサーバーをバックグラウンドで起動する例
    - command: "$(wslpath -u \"$USERPROFILE\")/scoop/apps/nodejs/current/npx @playwright/mcp@latest --port 8931 --browser msedge"
      description: "Playwright MCPサーバーを起動"
      host: true
      background: true
    # コンテナ内で実行する前提条件の例
    # - command: "npm install -g some-package"
    #   description: "必要なパッケージをインストール"
    #   host: false

# 他のMCPサービスの例
# memory:
#   prerequisites:
#     - command: "mkdir -p /data/memory"
#       description: "メモリストレージディレクトリを作成"
#       host: false
