gui:
  language: 'ja'
  showIcons: true

git:
  pagers:
    - pager: delta --dark --paging=never --no-gitconfig --true-color=auto --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

os:
  edit: "nvim \"{{filename}}\""
  copyToClipboardCmd: 'echo {{text}} | $HOME/.dotfiles/bin/tmux-copy'

customCommands:
  - key: "w"
    description: "git wt (create/switch, no cd)"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "worktree/branch name"
        initialValue: ""
    command: "git wt --nocd '{{index .PromptResponses 0}}'"
