memodir = "$HOME/.config/memo/_posts"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "$HOME/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
