[mgr]
prepend_keymap = [
	{ on = "<C-r>", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
	{ on = "<C-f>", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
	{ on = "z", run = "noop", desc = "Disable fzf on z" },
    { on = "o",     run = ['shell -- tmux new-window nvim $@'],   desc = "Open in tmux window" },
]
