---
name: openjdk-17
description: |
  The Microsoft Build of OpenJDK is a no-cost distribution of OpenJDK that's open source and available for free for anyone to deploy anywhere.
  It includes Long-Term Support (LTS) binaries for Java 11 and Java 17 on x64 server and desktop environments on macOS, Linux, and Windows,
  AArch64/ARM64 on Linux and Windows, binaries for macOS on Apple Silicon (AArch64/M1), and musl libc compiled binaries for Alpine Linux on x64.
homepage: https://learn.microsoft.com/en-us/java/openjdk/
licenses:
  - GPL-2.0
languages:
  - Java
categories:
  - Runtime

source:
  id: pkg:generic/java/openjdk@17.0.17
  download:
    - target: darwin_x64
      files:
        openjdk-17.0.17.tar.gz: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-macos-x64.tar.gz
      bin: jdk-17.0.17.jdk/Contents/Home/bin
      java: java
      javac: javac
    - target: darwin_arm64
      files:
        openjdk-17.0.17.tar.gz: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-macos-aarch64.tar.gz
      bin: jdk-17.0.17.jdk/Contents/Home/bin
      java: java
      javac: javac

    - target: linux_x64
      files:
        openjdk-17.0.17.tar.gz: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-linux-x64.tar.gz
      bin: jdk-17.0.17/bin
      java: java
      javac: javac
    - target: linux_arm64
      files:
        openjdk-17.0.17.tar.gz: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-linux-aarch64.tar.gz
      bin: jdk-17.0.17/bin
      java: java
      javac: javac

    - target: win_x64
      files:
        openjdk-17.0.17.zip: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-windows-x64.zip
      bin: jdk-17.0.17/bin
      java: java.exe
      javac: javac.exe
    - target: win_arm64
      files:
        openjdk-17.0.17.zip: https://aka.ms/download-jdk/microsoft-jdk-17.0.17-windows-aarch64.zip
      bin: jdk-17.0.17/bin
      java: java.exe
      javac: javac.exe
bin:
  java: "{{source.download.bin}}/{{source.download.java}}"
  javac: "{{source.download.bin}}/{{source.download.javac}}"
