# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu-18_04:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: change permission
      run: chmod +x bin/setup.sh
    - name: Initialize dotfiles
      run: bin/setup.sh init
    - name: Deploy dotfiles
      run: bin/setup.sh deploy

  build-ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: change permission
      run: chmod +x bin/setup.sh
    - name: Initialize dotfiles
      run: bin/setup.sh init
    - name: Deploy dotfiles
      run: bin/setup.sh deploy

  build-ubuntu-22_04:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: change permission
      run: chmod +x bin/setup.sh
    - name: Initialize dotfiles
      run: bin/setup.sh init
    - name: Deploy dotfiles
      run: bin/setup.sh deploy
